pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "sandeshpawar17/helloworld-python:latest"
        GIT_REPO = '172.16.23.46/sandesh/helloworld-ci.git'
        GIT_BRANCH = 'main'
    }

    stages {
        stage('Checkout and Build') {
            steps {
                script {
                    // Checkout code and build Docker image in one step
                    withCredentials([usernamePassword(credentialsId: 'gitlab_id', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
                        sh """
                            git clone http://\$GIT_USERNAME:\$GIT_PASSWORD@$GIT_REPO
                            cd helloworld-ci
                            git checkout \$GIT_BRANCH
                            docker build -t ${DOCKER_IMAGE} .
                        """
                    }
                }
            }
        }

        stage('Login and Push Docker Image') {
            steps {
                script {
                    // Login to Docker Hub and push the image in one step
                    withCredentials([usernamePassword(credentialsId: 'dockerhub_id', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh """
                            docker login -u \$DOCKER_USERNAME -p \$DOCKER_PASSWORD
                            docker push ${DOCKER_IMAGE}
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            // Clean up the Docker image after pushing
            sh "docker rmi ${DOCKER_IMAGE}"
        }

        success {
            echo "Docker image successfully pushed."
        }

        failure {
            echo "Error during the build process."
        }
    }
}
